### ISSUE TITLE
What about ios compatibility. Will app store let me to publish it? 

### ISSUE THREAD

**Issue by armsofter** [MobileChromeApps/cordova-plugin-background-app#2]

**Comment by armsofter** [comment]
Is there anyone that have published app in app store with this plugin?

**Comment by vahidreza** [comment]
@armsofter 
hi
did you try to publish an app with this plugin? was it approved?

**Comment by kosssi** [comment]
@agrieve, @jpchase, @armsofter, @vahidreza

Have you a response of this question?

Thanks
